# Generated by Django 4.1.2 on 2022-10-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='ranking',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
