# Generated by Django 4.1.2 on 2022-10-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0002_alter_basket_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='ranking',
            field=models.JSONField(blank=True, default='LOADING...', null=True),
        ),
    ]
