# Generated by Django 4.1.2 on 2022-10-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0003_alter_basket_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='ranking',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
