# Generated by Django 4.1.2 on 2022-10-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0004_alter_basket_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket',
            field=models.JSONField(null=True),
        ),
    ]
