# Generated by Django 4.1.2 on 2022-10-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0005_alter_basket_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='ranking',
        ),
    ]
