# Generated by Django 4.1.3 on 2022-11-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0011_alter_basket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='search_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
