version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000" 
    volumes:
      - ./app:/app
    container_name: django_app
    # command: >
    #   sh -c "python3 manage.py migrate &&
    #          python3 manage.py wait_for_db &&
    #          python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    tty: true
  
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: postgres_db
    env_file:
      - ./.env.dev
  
  redis:
    image: redis:alpine
    container_name: redis
  
  celery:
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    volumes:
      - ./app:/app
    container_name: celery
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app

volumes:
  pgdata:
